# Generated by Django 4.2.6 on 2023-10-28 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_order_stripe_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_payment_intent',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
